/**
 * Single source of truth for document categories visible in `/vault`.
 *
 *  - user-uploaded via the vault directly:  incorporation | nda | tax_return | other
 *  - written by parent flows (auto):        contract | invoice | paystub | receipt | slip
 *
 * The `documents.category` column is TEXT (not an enum) so the DB accepts
 * any value; we gate writes in-app. If an unknown value ever shows up, the
 * vault table renders it with a neutral "unknown" pill.
 */
import type { Tone } from "@/lib/tones";

export const VAULT_CATEGORIES = [
  "incorporation",
  "contract",
  "nda",
  "receipt",
  "invoice",
  "paystub",
  "tax_return",
  "slip",
  "other",
] as const;
export type VaultCategory = (typeof VAULT_CATEGORIES)[number];

/** Categories a user can pick in the vault "Upload" dialog. The `contract`
 * category is special: when picked, the upload dialog also requires a
 * contract picker. Primary contract PDFs (uploaded via /clients) ALSO carry
 * category=contract — they're parent-owned by `contracts.documentId`. The
 * UI distinguishes the two via resolveParentLinks. */
export const USER_UPLOADABLE: readonly VaultCategory[] = [
  "incorporation",
  "nda",
  "contract",
  "tax_return",
  "other",
];

/** Categories that always come from a parent flow — vault shows them
 * read-mostly + delete disabled while linked. NOTE: `contract` is omitted
 * here because vault-uploaded contract attachments are vault-owned. The
 * primary contract PDF is parent-owned, but that's detected at runtime by
 * `resolveParentLinks` checking `contracts.documentId` references. */
export const PARENT_OWNED: readonly VaultCategory[] = [
  "invoice",
  "paystub",
  "receipt",
  "slip",
];

export const CATEGORY_LABEL: Record<VaultCategory, string> = {
  incorporation: "Incorporation",
  contract: "Contract",
  nda: "NDA",
  receipt: "Receipt",
  invoice: "Invoice",
  paystub: "Paystub",
  tax_return: "Tax return",
  slip: "Year-end slip",
  other: "Other",
};

export const CATEGORY_TONE: Record<VaultCategory, Tone> = {
  incorporation: "indigo",
  contract: "emerald",
  nda: "violet",
  receipt: "amber",
  invoice: "emerald",
  paystub: "cyan",
  tax_return: "sky",
  slip: "indigo",
  other: "rose",
};

export function isVaultCategory(s: string): s is VaultCategory {
  return (VAULT_CATEGORIES as readonly string[]).includes(s);
}

export function isUserUploadable(c: VaultCategory): boolean {
  return USER_UPLOADABLE.includes(c);
}

/** Human-readable short description for the upload dialog help text. */
export const CATEGORY_HINT: Record<VaultCategory, string> = {
  incorporation: "Articles of incorporation, shareholder agreements, directors' resolutions.",
  nda: "NDAs signed with clients or partners.",
  tax_return: "Filed T2 / T1 / HST / payroll returns kept for records.",
  other: "Anything else — receipts you're not tracking in expenses, letters, misc PDFs.",
  contract: "Ancillary docs tied to a contract — insurance, code of conduct, addendums. Pick the contract on upload.",
  invoice: "Auto-generated by /invoices on PDF render.",
  paystub: "Auto-generated by /paycheques on PDF render.",
  receipt: "Auto-generated by /expenses when a receipt is attached.",
  slip: "Auto-generated by /slips when a T4 or T5 is filed.",
};
